workflows:
  ios:
    name: Build iOS
    environment:
      vars:
        - name: FLUTTER_CHANNEL
          value: stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Build iOS app
          command: |
            cordova build ios --device --release
      - upload-artifact:
          path: platforms/ios/build/emulator/*.ipa
