workflows:
  ios:
    name: Build iOS
    environment:
      flutter: stable
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Build iOS app
          command: |
            cordova build ios --release
      - archive:
          directory: platforms/ios/build/device
          output: build/ios-app.ipa
